### ISSUE TITLE
How to debug the code in pyCharm(macOS) ,can you please explain code flow?

### ISSUE THREAD

**Issue by kyolxs** [kmaehashi/pypict#8]
When I execute the code below：
`import pypict.tools

params = {
    "Type":          ["Single", "Span", "Stripe", "Mirror", "RAID-5"],
    "Size":          ["10", "100", "500", "1000", "5000", "10000", "40000"],
    "Format method": ["Quick", "Slow"],
    "File system":   ["FAT", "FAT32", "NTFS"],
    "Cluster size":  ["512", "1024", "2048", "4096", "8192", "16384", "32768", "65536"],
    "Compression":   ["On", "Off"],
}

for case in pypict.tools.from_dict(params):
    print(case)`

I got this error：
`Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pypict.tools
  File "/Users/name/Desktop/pypict/pypict/__init__.py", line 3, in <module>
    from pypict.api import Task
  File "/Users/name/Desktop/pypict/pypict/api.py", line 1, in <module>
    from pypict import capi
ImportError: cannot import name capi`

thx.

**Comment by kmaehashi** [comment]
I guess you haven't installed `pypict`. You need to install using `pip install -U .` https://github.com/kmaehashi/pypict#installation

**Comment by kyolxs** [comment]
> I guess you haven't installed `pypict`. You need to install using `pip install -U .` https://github.com/kmaehashi/pypict#installation

Oh, thank you, I will try again.
